[package]
name = "sim-events"
version.workspace = true
edition.workspace = true

[features]
default = []
test-fixtures = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
